### PR TITLE
Feature: optionally hash file path and mod time

### LINKED ISSUE #12: Make including path info in hash a kwarg
As discussed in person, it would be handy to have the option to not include the filename and modification time in the `"binhash"`.

### PR DESCRIPTION
**Pull request by dougiesquire**
I've added a few `**kwargs` to the signatures of some Manifest methods to allow passing kw options through to the `hash` function.

I haven't added a test for this as there wasn't an obvious/quick place from my brief scan through. Happy to add one though if we think it's worthwhile. Incidentally, 3 tests failed before I made any changes at all. I haven't looked into this yet.

Closes #12

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
> I haven't added a test for this as there wasn't an obvious/quick place from my brief scan through. Happy to add one though if we think it's worthwhile

It's usually worthwhile, but it's been so long since I touched this I'd have to take a few minutes to have a useful suggestion about where it could be slotted in.

At the very least could copy an existing test and monkey about with names/timestamps to check it still works.

> Incidentally, 3 tests failed before I made any changes at all

Ooops. 😊

**Comment by dougiesquire** [comment]
> Incidentally, 3 tests failed before I made any changes at all

This was actually an issue with my env, not with the tests - I didn't have `ncdump` available, whoops

**Comment by dougiesquire** [comment]
Ready for you to take a look @aidanheerdegen

**Comment by aidanheerdegen** [comment]
Don't hate me @dougiesquire, because I think I suggested the `**kwargs` approach, but I'm wondering how the `**kwargs` can be passed to the function the way the code (I wrote) currently works.

AFAICT the only way to influence the hashing function is with a name. So to have a `binhash` which ignores `mtime` would require a hash function with a unique name, e.g. `binhash-nomtime`, and one that is only size might be `binhash-sizeonly`. 

Am I wrong? 

If I'm not then I'd suggest making a `binhash` function in `yamanifest/hashing.py` that accepts the `include_filename` and `include_mtime` args, and then make aliases to versions like `binhash-sizeonly` using [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial).

**Comment by dougiesquire** [comment]
I'm possibly misunderstanding what you're saying, but my approach to this was to add `**kwargs` to the function signatures of Manifest methods `Manifest.add()` and `Manifest.check_file()`. The kwargs get passed on to `Manifest.calc_hashes()` and then to `hashing.hash()`. I realise now that I missed `Manifest.check()`, which calls `Manifest.check_file()` and already has `**args` in its function signature, so that won't work...

Another approach would be to add a `hash_kwargs=None` to the function signatures, e.g.:
```
mf = Manifest("mf.yml")
mf.add(filenames, ["binhash"], hash_kwargs={"include_mtime": False})
```
I think I've seen something like this before in xarray, but I can't find it now ([xarray interp](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.interp.html) is the closest I can find).

I'm very happy to add hashfns `"binhash-sizeonly"` etc as you suggest, but just thought I'd throw that out there. Your approach is probably better as the `include_filenames` and `include_mtime` kwargs only apply to `"binhash"` anyway.

**Comment by aidanheerdegen** [comment]
> I'm very happy to add hashfns `"binhash-sizeonly"` etc as you suggest, but just thought I'd throw that out there. Your approach is probably better as the `include_filenames` and `include_mtime` kwargs only apply to `"binhash"` anyway.

Believe me, I *dislike intensely* the idea of `binhash-sizeonly`, that is so ugly, so if you can think of a better name then please do so. I'm just trying to work with the crappy architecture the clown who wrote this (me) left us with.

The hashes used are defined as text keys **in the manifest files**, e.g. 
```yaml
work/atmosphere/yatm_d750b4b.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/yatm_d750b4b.exe
  hashes:
    binhash: 52a975e3d202c0047a9ec9be1346c23c
    md5: fcc373fb59917cada96c2776201b362d
```
I can't see how you'd add arguments to these. This is why I suggested the nutty name approach.

Happy to be schooled in how the code I wrote is actually better than I thought though.

**Comment by dougiesquire** [comment]
Sorry yes, I'm being a _total_ idiot - sometimes I surprise even myself...

**Comment by aidanheerdegen** [comment]
No way, no dumb questions. It's all good documentation when someone comes to look this stuff up.

**Comment by dougiesquire** [comment]
Question: what is the advantage to using partial functions here over just passing the args as I've done in my latest commits?

**Comment by aidanheerdegen** [comment]
> Question: what is the advantage of using partial functions here over just passing the args as I've done in my latest commits?

None. What you've done is better. Sorry for not replying sooner.

**Review by aidanheerdegen — APPROVED** [review]

**Comment by dougiesquire** [comment]
@aidanheerdegen would you mind merging? I don't have permission

**Pull request merged**
